name: Run Cypress Test on Fearless Vegetarian Website
on:
 push:
   branches:
     - main
jobs:
 Cypress-Test:
   runs-on: ubuntu-latest
   steps:
     - name: Checkout GitCode
       uses: actions/checkout@v3
     - name: Cypress run
       uses: cypress-io/github-action@v5
       with:
         command: npx cypress run
         browser: chrome
